const DAMAGE_TYPE = {
    IMPACT: 1,
    PUNCTURE: 2,
    SLASH: 4,
    COLD: 8,
    ELECTRIC: 16,
    HEAT: 32,
    TOXIN: 64,
    BLAST: 40,
    CORROSIVE: 80,
    GAS: 96,
    MAGNETIC: 24,
    RADIATION: 48,
    VIRAL: 72,
    TRUE: 128,
    VOID: 256
}

function isElement(damageType) {
    return [DAMAGE_TYPE.COLD, DAMAGE_TYPE.ELECTRIC, DAMAGE_TYPE.HEAT, DAMAGE_TYPE.TOXIN,
        DAMAGE_TYPE.MAGNETIC, DAMAGE_TYPE.BLAST, DAMAGE_TYPE.RADIATION, DAMAGE_TYPE.VIRAL,
        DAMAGE_TYPE.CORROSIVE, DAMAGE_TYPE.GAS].includes(damageType);
}

function isPrimaryElement(damageType) {
    return [DAMAGE_TYPE.COLD, DAMAGE_TYPE.ELECTRIC, DAMAGE_TYPE.HEAT, DAMAGE_TYPE.TOXIN].includes(damageType);
}

function breakDownSecondaryElement(damageType) {
    switch (damageType) {
        case DAMAGE_TYPE.BLAST:
            return [DAMAGE_TYPE.COLD, DAMAGE_TYPE.HEAT];
        case DAMAGE_TYPE.CORROSIVE:
            return [DAMAGE_TYPE.ELECTRIC, DAMAGE_TYPE.TOXIN];
        case DAMAGE_TYPE.GAS:
            return [DAMAGE_TYPE.HEAT, DAMAGE_TYPE.TOXIN];
        case DAMAGE_TYPE.MAGNETIC:
            return [DAMAGE_TYPE.COLD, DAMAGE_TYPE.ELECTRIC];
        case DAMAGE_TYPE.RADIATION:
            return [DAMAGE_TYPE.ELECTRIC, DAMAGE_TYPE.HEAT];
        case DAMAGE_TYPE.VIRAL:
            return [DAMAGE_TYPE.COLD, DAMAGE_TYPE.TOXIN];
    }

}

const ModRarity = {
    COMMON: 1,
    UNCOMMON: 2,
    RARE: 4,
    LEGENDARY: 8,
    RIVEN: 16,
    PECULIAR: 32,
    AMALGAM: 64
}

// TODO write examples of mods with these effects in comments
const MOD_EFFECT_TYPE = {
    DAMAGE: 10,     //Done
    MULTISHOT: 11,  //Done

    CRITICAL_CHANCE: 20,        //Done
    CRITICAL_DAMAGE: 21,        //Done
    STATUS_CHANCE: 22,          //Done
    STATUS_CHANCE_ADDITIVE: 24, //Done
    STATUS_DURATION: 23,        //Done

    IMPACT: 30,     //Done
    PUNCTURE: 31,   //Done
    SLASH: 32,      //Done

    COLD: 40,       //Done
    ELECTRIC: 41,   //Done
    HEAT: 42,       //Done
    TOXIN: 43,      //Done

    BLAST: 50,      //Done
    CORROSIVE: 51,  //Done
    GAS: 52,        //Done
    MAGNETIC: 53,   //Done
    RADIATION: 54,  //Done
    VIRAL: 55,      //Done

    FIRE_RATE: 60,          //Done
    RELOAD_SPEED: 61,       //Done
    MAGAZINE_CAPACITY: 62,  //Done
    AMMO_CAPACITY: 63,      //Done

    BANE_OF_GRINEER: 70,        //Done
    DAMAGE_TO_GRINEER: 70,      //Done
    BANE_OF_CORPUS: 71,         //Done
    DAMAGE_TO_CORPUS: 71,       //Done
    BANE_OF_INFESTED: 72,       //Done
    DAMAGE_TO_INFESTED: 72,     //Done
    BANE_OF_CORRUPTED: 73,      //Done
    DAMAGE_TO_CORRUPTED: 73,    //Done

    PUNCH_THROUGH: 80,
    ACCURACY: 81,
    SPREAD: 82,
    RECOIL: 83,
    FLIGHT_SPEED: 84,
    ZOOM: 85,
    BEAM_RANGE: 86,
    BLAST_RADIUS: 87,
    NOISE_REDUCTION: 88,
    STICK_CHANCE: 89,
    MAGAZINE_CAPACITY_ADDITIVE: 90,
    LIFE_STEAL: 91,
    FLIGHT_DISTANCE: 92,

    HEADSHOT_DAMAGE: 100,
    FIRST_SHOT_DAMAGE: 101,
    LAST_SHOT_DAMAGE: 102,
    EXPLOSION_CHANCE: 103,
    BODY_EXPLOSION_DAMAGE: 104,
    HEADSHOT_KILL_ENERGY: 105,
    DEAD_AIM: 106,
    AMMO_EFFICIENCY: 107,
    DAMAGE_PER_STATUS: 108,

    AMMO_MUTATION: 120,
    COMBO_DURATION: 121,
    HOLSTER_RELOAD: 122,
    HOLSTER_RELOAD_ALL: 123,
    AMMO_MUTATION_SHOTGUN_SNIPER: 124,
    AMMO_MUTATION_RIFLE_PISTOL: 125,
    KILL_ENEMY_REFILL_AMMO: 126,
    BODYSHOT_DAMAGE: 127,

    RICOCHET_BOUNCE: 130,
    GORE_CHANCE: 131,

    DAGGERS_REDUCE_ARMOR: 150,
    ARGONAK_REVEAL_PUNCH_THROUGH: 151,
    LIFE_STEAL_ON_NIKANAS: 152,
    DAIKYU_PICKUP_ARROWS: 153,
    BLAST_RADIUS_FROM_MELEE: 154,
    FURAX_MELEE_KILL_KNOCKDOWN: 155,
    SHIELD_BLOCK_COMBO_COUNT: 156,
    SHOTGUN_RELOAD_SPEED: 157,

    HUNTER_MUNITIONS_EFFECT: 200,
    PROPORTIONAL_HEALTH_EXPLOSION: 201,
    INTERNAL_BLEEDING_EFFECT: 202,

    VIGILANTE_SET_EFFECT: 300,

    MITER_POP_NULLIFIER: 400,
    SILVA_AEGIS_BLOCK_CHARGE: 401,
    OBEX_FINISH_EXPLOSION: 402,
    LANKA_FLYING_SHOCK: 403,
    PANTHERA_SECONDARY_DISARM: 404,
    PENTA_TETHER: 405,
    FLUX_RIFLE_STATUS_FLUC_MIN: 406, //TODO
    FLUX_RIFLE_STATUS_FLUC_MAX: 407, //TODO
    DETRON_KILL_EXPLOSION: 408,
    PROVA_CHARGE_SHOCK: 409,
    SILVA_AEGIS_BLOCK_REDIRECT: 411,
    JAT_KITTAG_KILL_EXPLOSION: 412,
    SOBEK_KILL_EXPLOSION: 413,
    TWIN_BASOLK_CHARGE_TELEPORT: 414,
    OGRIS_NAPALM: 415, //TODO
    RIPKAS_PRONE_DAMAGE: 416,
    RIPKAS_PRONE_STATUS_CHANCE: 417,
    GRAKATA_EMPTY_MAGAZINE: 418,
    MUTALIST_QUANTA_MASS: 419, //TODO
    PENTA_NAPALM: 420, //TODO
    CONVECTRIX_EFFICIENCY: 421,
    BRONCO_CLOSE_STUN: 422,
    LATRON_NEXT_SHOT_BONUS: 423,
    LATRON_NEXT_SHOT_BONUS_BUFF: 423.5,
    DAIKYU_DISTANCE_DAMAGE: 424, //TODO
    PARIS_STATUS_RESTORE_HEALTH: 425,
    SOMA_PRIME_HIT_CRITICAL: 426, //TODO

    SPRINT_SPEED: 1020,
    DODGE_SPEED: 1021,
    MOVE_SPEED_AIMING: 1023,
    BULLET_JUMP: 1030,
    AIM_GLIDE: 1031,
    WALL_LATCH: 1032,
    HOLSTER_SPEED: 1040,
    IGNORE_STAGGER: 1041,
    REVIVE_SPEED: 1042,

    DURATION: 2000,
    RADIUS: 2001,
    RADIUS_RELATIVE_EXPLOSION: 2002,

    JUSTICE: 4000,
    TRUTH: 4001,
    ENTROPY: 4002,
    SEQUENCE: 4003,
    BLIGHT: 4004,
    PURITY: 4005
}

const WEAPON_TYPE = {
    RIFLE: 1,
    SHOTGUN: 2,
    PISTOL: 4,
    BOW: 8,
    UNIQUE: 16,
    PRIMARY: 1024,
    ASSAULT_RIFLE: 1025,
    SNIPER: 1026,
    CONTINUOUS: 1027,
    PISTOL_UNIQUE: 1028,
    PISTOL_CONTINUOUS: 1029,
    ALL_DUAL_CLEAVERS: 8000,
    ALL_SOBEK: 8001,
    ONLY_HEK: 8002,
    ALL_MITER: 8003,
    ALL_JAW_SWORD: 8004,
    ONLY_BURSTON_PRIME: 8005,
    ALL_VIPER: 8006,
    ALL_SILVA_AEGIS: 8007,
    ALL_SUPRA: 8008,
    ALL_KESTREL: 8009,
    ALL_BOLTO: 8010,
    ALL_OBEX: 8011,
    ALL_GRINLOK: 8012,
    ALL_SPECTRA: 8013,
    ALL_ACRID: 8014,
    ALL_LANKA: 8015,
    ALL_EMBOLIST: 8016,
    ALL_DARK_DAGGER: 8017,
    ALL_MIRE: 8018,
    ALL_KUNAI: 8019,
    ALL_SKANA: 8020,
    ALL_VULKAR: 8021,
    ALL_FURIS: 8022,
    ALL_PANTHERA: 8023,
    ALL_PENTA: 8024,
    ALL_FLUX_RIFLE: 8025,
    ALL_DETRON: 8026,
    ALL_PROVA: 8027,
    ALL_TETRA: 8028,
    ALL_JAT_KITTAG: 8029,
    ALL_TWIN_BASOLK: 8030,
    ALL_OGRIS: 8031,
    ALL_DRAKGOON: 8032,
    ALL_RIPKAS: 8033,
    ALL_GRAKATA: 8034,
    ALL_MUTALIST_QUANTA: 8035,
    ALL_CONVECTRIX: 8036,
    ALL_HARPAK: 8037,
    ALL_MAGNUS: 8038,
    ALL_BRONCO: 8039,
    ALL_TONKOR: 8040,
    ALL_ARGONAK: 8041,
    ALL_DAIKYU: 8042,
    ALL_FURAX: 8043,
    ALL_JAVLOK: 8044,
    ALL_RUBICO: 8045,
    ALL_LATRON: 8046,
    ALL_MARELOK: 8047,
    ONLY_PARIS_PRIME: 8048,
    ONLY_AKBRONCO_PRIME: 8049,
    ONLY_SOMA_PRIME: 8050,
    ONLY_AKSTILETTO_PRIME: 8051,
    UNIVERSAL: 9999
}

/**
 * Converts an elemental mod effect to its corresponding damage type.
 * @param modEffectType
 * @returns {number} damageType
 */
function elementalModEffectToDamage(modEffectType) {
    return DAMAGE_TYPE[Object.keys(MOD_EFFECT_TYPE).find(key => MOD_EFFECT_TYPE[key] === modEffectType)];
}

/**
 *
 * @returns {number[]} - List of all mod effect types which contribute to damage output or otherwise affect kill time.
 */
function usefulModEffectTypes() {
    return [MOD_EFFECT_TYPE.DAMAGE,
        MOD_EFFECT_TYPE.MULTISHOT,
        MOD_EFFECT_TYPE.CRITICAL_CHANCE,
        MOD_EFFECT_TYPE.CRITICAL_DAMAGE,
        MOD_EFFECT_TYPE.STATUS_CHANCE,
        MOD_EFFECT_TYPE.STATUS_CHANCE_ADDITIVE,
        MOD_EFFECT_TYPE.STATUS_DURATION,
        MOD_EFFECT_TYPE.IMPACT,
        MOD_EFFECT_TYPE.PUNCTURE,
        MOD_EFFECT_TYPE.SLASH,
        MOD_EFFECT_TYPE.COLD,
        MOD_EFFECT_TYPE.ELECTRIC,
        MOD_EFFECT_TYPE.HEAT,
        MOD_EFFECT_TYPE.TOXIN,
        MOD_EFFECT_TYPE.BLAST,
        MOD_EFFECT_TYPE.CORROSIVE,
        MOD_EFFECT_TYPE.GAS,
        MOD_EFFECT_TYPE.MAGNETIC,
        MOD_EFFECT_TYPE.RADIATION,
        MOD_EFFECT_TYPE.VIRAL,
        MOD_EFFECT_TYPE.FIRE_RATE,
        MOD_EFFECT_TYPE.RELOAD_SPEED,
        MOD_EFFECT_TYPE.MAGAZINE_CAPACITY,
        MOD_EFFECT_TYPE.AMMO_CAPACITY,
        MOD_EFFECT_TYPE.DAMAGE_TO_GRINEER,
        MOD_EFFECT_TYPE.DAMAGE_TO_CORPUS,
        MOD_EFFECT_TYPE.DAMAGE_TO_INFESTED,
        MOD_EFFECT_TYPE.DAMAGE_TO_CORRUPTED,
        MOD_EFFECT_TYPE.MAGAZINE_CAPACITY_ADDITIVE,
        MOD_EFFECT_TYPE.HEADSHOT_DAMAGE,
        MOD_EFFECT_TYPE.FIRST_SHOT_DAMAGE,
        MOD_EFFECT_TYPE.LAST_SHOT_DAMAGE,
        MOD_EFFECT_TYPE.EXPLOSION_CHANCE,
        MOD_EFFECT_TYPE.BODY_EXPLOSION_DAMAGE,
        MOD_EFFECT_TYPE.DEAD_AIM,
        MOD_EFFECT_TYPE.AMMO_EFFICIENCY,
        MOD_EFFECT_TYPE.COMBO_DURATION,
        MOD_EFFECT_TYPE.BODYSHOT_DAMAGE,

        // TODO not sure which of these affect damage
        MOD_EFFECT_TYPE.DAGGERS_REDUCE_ARMOR,
        MOD_EFFECT_TYPE.BLAST_RADIUS_FROM_MELEE,
        MOD_EFFECT_TYPE.SHIELD_BLOCK_COMBO_COUNT,
        MOD_EFFECT_TYPE.SHOTGUN_RELOAD_SPEED,
        MOD_EFFECT_TYPE.HUNTER_MUNITIONS_EFFECT,
        MOD_EFFECT_TYPE.INTERNAL_BLEEDING_EFFECT,
        MOD_EFFECT_TYPE.VIGILANTE_SET_EFFECT,
        MOD_EFFECT_TYPE.MITER_POP_NULLIFIER,
        MOD_EFFECT_TYPE.SILVA_AEGIS_BLOCK_CHARGE,
        MOD_EFFECT_TYPE.OBEX_FINISH_EXPLOSION,
        MOD_EFFECT_TYPE.LANKA_FLYING_SHOCK,
        MOD_EFFECT_TYPE.PANTHERA_SECONDARY_DISARM,
        MOD_EFFECT_TYPE.PENTA_TETHER,
        MOD_EFFECT_TYPE.FLUX_RIFLE_STATUS_FLUC_MIN,
        MOD_EFFECT_TYPE.FLUX_RIFLE_STATUS_FLUC_MAX,
        MOD_EFFECT_TYPE.DETRON_KILL_EXPLOSION,
        MOD_EFFECT_TYPE.PROVA_CHARGE_SHOCK,
        MOD_EFFECT_TYPE.SILVA_AEGIS_BLOCK_REDIRECT,
        MOD_EFFECT_TYPE.JAT_KITTAG_KILL_EXPLOSION,
        MOD_EFFECT_TYPE.SOBEK_KILL_EXPLOSION,
        MOD_EFFECT_TYPE.TWIN_BASOLK_CHARGE_TELEPORT,
        MOD_EFFECT_TYPE.OGRIS_NAPALM,
        MOD_EFFECT_TYPE.RIPKAS_PRONE_DAMAGE,
        MOD_EFFECT_TYPE.RIPKAS_PRONE_STATUS_CHANCE,
        MOD_EFFECT_TYPE.GRAKATA_EMPTY_MAGAZINE,
        MOD_EFFECT_TYPE.MUTALIST_QUANTA_MASS,
        MOD_EFFECT_TYPE.PENTA_NAPALM,
        MOD_EFFECT_TYPE.CONVECTRIX_EFFICIENCY,
        MOD_EFFECT_TYPE.BRONCO_CLOSE_STUN,
        MOD_EFFECT_TYPE.LATRON_NEXT_SHOT_BONUS,
        MOD_EFFECT_TYPE.LATRON_NEXT_SHOT_BONUS_BUFF,
        MOD_EFFECT_TYPE.DAIKYU_DISTANCE_DAMAGE,
        MOD_EFFECT_TYPE.PARIS_STATUS_RESTORE_HEALTH,
        MOD_EFFECT_TYPE.SOMA_PRIME_HIT_CRITICAL]
}

/**
 *
 * @returns {number[]} - List of all elemental mod effect types (4 primary, 6 secondary).
 */
function elementalModEffectTypes() {
    return [MOD_EFFECT_TYPE.COLD,
        MOD_EFFECT_TYPE.ELECTRIC,
        MOD_EFFECT_TYPE.HEAT,
        MOD_EFFECT_TYPE.TOXIN,
        MOD_EFFECT_TYPE.BLAST,
        MOD_EFFECT_TYPE.CORROSIVE,
        MOD_EFFECT_TYPE.GAS,
        MOD_EFFECT_TYPE.MAGNETIC,
        MOD_EFFECT_TYPE.RADIATION,
        MOD_EFFECT_TYPE.VIRAL]
}

const SIMULATION = {
    SLOW_KILL_TIME: 25, // if a round takes more than this many seconds, we only need SLOW_ITERATIONS many rounds
    SLOW_ITERATIONS: 2, // the number of iterations to run for slow builds
}

module.exports = {
    DAMAGE_TYPE,
    isElement,
    isPrimaryElement,
    breakDownSecondaryElement,
    ModRarity,
    MOD_EFFECT_TYPE,
    WEAPON_TYPE,
    elementalModEffectToDamage,
    usefulModEffectTypes,
    elementalModEffectTypes,
    SIMULATION
}